### ISSUE TITLE
Is it possible to tell when something has left view?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/whenInView#3]
Maybe using offsets? If so, lets add an example.

**Comment by johndigital** [comment]
Yes, if `removeWhenOut` is set to true then by default the class will be removed when the element is completely out of view.

**Comment by drewbaker** [comment]
But I need to add a class to something when it's out of view. 

Like, when scrolled down, and slideshow out of view, add "dark-background" to body.

Maybe that is beyond the scope of this plugin.

**Comment by johndigital** [comment]
No, you can totally do that! just define the `elementOut` property as a function, it will be fired whenever the element is completely out of view.
