### ISSUE TITLE
Mising semi-colon

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/whenInView#4]
I get this error:

![screen shot 2016-12-02 at 2 29 07 pm](https://cloud.githubusercontent.com/assets/475015/20822081/d8b7484a-b89b-11e6-99f9-e8c7d50ae0f5.png)

**Comment by drewbaker** [comment]
Seems to only be in minifed version

**Comment by SaFrMo** [comment]
Fixed in latest commit!
